# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

---

ci:
  skip: [check-manifest]

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # Changes tabs to spaces
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus, --keep-mock]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        # This is a slow hook, so only run this if --hook-stage manual is passed
        stages: [manual]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.0
    hooks:
      - id: blacken-docs
        args: [-S, -l, '120']
        additional_dependencies: [black==22.3.0]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8-strict
        exclude: ^(.*_test\.py)$
        additional_dependencies: [flake8-comprehensions, flake8-breakpoint,
                                  flake8-eradicate, flake8-mutable,
                                  flake8-docstrings]
      - id: flake8
        name: flake8-test-files
        additional_dependencies: [flake8-comprehensions, flake8-breakpoint,
                                  flake8-eradicate, flake8-mutable]
        files: ^(.*_test\.py)$

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a5'
    hooks:
      - id: pylint
        args: ['--score=n']
        # This is a slow hook, so only run this if --hook-stage manual is passed
        stages: [manual]
        additional_dependencies: [pybind11>=2.6, numpy, requests, boto3, matplotlib, networkx, sympy]

  - repo: https://github.com/mgedmin/check-manifest
    rev: '0.50'
    hooks:
      - id: check-manifest
        additional_dependencies: ['setuptools-scm', 'pybind11>=2.6']
